### ISSUE TITLE
Unexpected results from SPARQL CONSTRUCT with blank nodes

### ISSUE THREAD

**Issue by milvala** [oxigraph/oxigraph#220]
Hi

I'm using SPARQL CONSTRUCT queries for the transformation steps in my ETL, but I'm noticing some strange behaviour with Pyoxigraph (and oxrdflib) when the input data contains blank nodes. 

In the code below I'm comparing Pyoxigraph, oxrdflib and plain rdflib and you can see that the former two result in plenty of (faulty/unexpected) results whereas the expected result would be just one simple triple (cf. the output from rdflib). I'm also including the input data and a (simplified version of) my SPARQL CONSTRUCT query.

Any help with what's going on would be much appreciated :smiley: 

**Python code:**
```
# necessary imports
import io
from pyoxigraph import *
from rdflib import Graph

# load rdf data from file
# create IO object for pyoxigraph
rdf_file = open("temp.nt", "r")
rdf_data = rdf_file.read()
rdf_file.close()
rdf_data_io = io.BytesIO(rdf_data.encode())

# initialize different graphs/stores
oxi_input_graph = Graph(store="Oxigraph")
oxi_output_graph = Graph(store="Oxigraph")
rdflib_input_graph = Graph()
rdflib_output_graph = Graph()
pyoxi_input_graph = Store()
pyoxi_output_graph = Store()

# load the input data in the relevant graphs/store
oxi_input_graph.parse(data=rdf_data, format="nt")
rdflib_input_graph.parse(data=rdf_data, format="nt")
pyoxi_input_graph.bulk_load(input=rdf_data_io, mime_type="application/n-triples")
pyoxi_input_graph.optimize()

# load the SPARQL query from file
query_file = open("./tl_companies_mapping_org.sparql", "r")
query = query_file.read()
query_file.close()

# query the different graphs/store
oxi_results = oxi_input_graph.query(query)
rdflib_results = rdflib_input_graph.query(query)
pyoxi_results = list(pyoxi_input_graph.query(query))

# add output from query to output graphs/store
for result in oxi_results:
    oxi_output_graph.add(result)

for result in rdflib_results:
    rdflib_output_graph.add(result)
    
for i in range(0,len(pyoxi_results)):
    (s,p,o) = pyoxi_results[i]
    pyoxi_output_graph.add(Quad(s,p,o,DefaultGraph()))
pyoxi_output_graph.optimize()

# print the different output graphs
print(rdflib_output_graph.serialize())
# results in:
#@prefix org: <http://www.w3.org/ns/org#> .
#
#<https://data.hetarchief.be/id/organisatie/6b570d9b244136be026e9d42805eeb83> a org:Site ;
#    org:siteAddress <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .

print(oxi_output_graph.serialize(format="nt"))
# results in:
#<https://data.hetarchief.be/id/organisatie/2a6ecabbc2fa60a0e89c809984172fd9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/2a6ecabbc2fa60a0e89c809984172fd9> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/6b570d9b244136be026e9d42805eeb83> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/6b570d9b244136be026e9d42805eeb83> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/e6cfc7f1c9cc2e3aa6fa57351c390da3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/e6cfc7f1c9cc2e3aa6fa57351c390da3> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/6e42274bc3d503bbce02065485a905fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# ...

print(str(pyoxi_output_graph))
# results in:
# <https://data.hetarchief.be/id/organisatie/2a6ecabbc2fa60a0e89c809984172fd9> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/2a6ecabbc2fa60a0e89c809984172fd9> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/6b570d9b244136be026e9d42805eeb83> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/6b570d9b244136be026e9d42805eeb83> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/e6cfc7f1c9cc2e3aa6fa57351c390da3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/e6cfc7f1c9cc2e3aa6fa57351c390da3> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/6e42274bc3d503bbce02065485a905fe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# <https://data.hetarchief.be/id/organisatie/6e42274bc3d503bbce02065485a905fe> <http://www.w3.org/ns/org#siteAddress> <https://data.hetarchief.be/id/organisatie/6ba39b4ca99aca7ed9b23abeb08c1dcd> .
# <https://data.hetarchief.be/id/organisatie/bfe62931641c1f93dc080b222041ca50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/org#Site> .
# ...
```

**Input data:**
```
_:ub2bL16C23 <https://data.hetarchief.be/ns/source#type> "businessType" .
_:ub2bL33C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL33C26 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "1\" audiotape" .
_:ub2bL76C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL76C26 .
_:ub2bL74C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL26C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL26C26 .
_:ub2bL38C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL38C26 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "1/4\" audiotape" .
_:ub2bL24C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL24C26 .
_:ub2bL33C26 <https://data.hetarchief.be/ns/source#id> "2245baba-81b2-0872-b159-9c553d323da7" .
_:ub2bL112C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL112C26 .
_:ub2bL120C26 <https://data.hetarchief.be/ns/source#id> "93ef05e1-c52b-0120-8852-b0e27582e43f" .
_:ub2bL109C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#language> "nl" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL21C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL44C9 .
_:ub2bL72C26 <https://data.hetarchief.be/ns/source#id> "5888fb72-503f-0165-a55b-113f48e23da8" .
_:ub2bL79C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL41C9 <https://data.hetarchief.be/ns/source#value> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL28C26 <https://data.hetarchief.be/ns/source#id> "9f0f8e69-1fe7-0d3c-8d5b-0bd324e66396" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#addresses> _:ub2bL11C19 .
_:ub2bL33C9 <https://data.hetarchief.be/ns/source#value> "CUL - kunstenorganisatie" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "audiocassette" .
_:ub2bL21C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL28C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL100C9 <https://data.hetarchief.be/ns/source#value> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL33C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL38C9 <https://data.hetarchief.be/ns/source#value> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL18C40 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL100C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#id> "bb5def60-32e5-06fc-a455-e53016923d9e" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL112C9 .
_:ub2bL98C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL98C26 .
_:ub2bL74C26 <https://data.hetarchief.be/ns/source#id> "61f6a334-a2a5-0cc1-8f5b-b793f386933d" .
_:ub2bL79C26 <https://data.hetarchief.be/ns/source#id> "98b1b8b5-4970-0422-a55a-17855b262f4b" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL30C9 .
_:ub2bL103C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL16C23 <https://data.hetarchief.be/ns/source#id> "aa805430-31a3-0667-b213-167923d41c13" .
_:ub2bL98C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "VHS" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL47C26 .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#group> "5 LDAP (niet Bewerken)" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "betacam SX" .
_:ub2bL72C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL81C26 .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#type> "single_line" .
_:ub2bL21C9 <https://data.hetarchief.be/ns/source#value> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL11C33 <https://data.hetarchief.be/ns/source#line_1> "Teststreet 99/100" .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#context> "company" .
_:ub2bL94C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL36C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL36C26 .
_:ub2bL79C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL79C26 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#added_at> "2021-12-16T16:06:46+00:00" .
_:ub2bL112C9 <https://data.hetarchief.be/ns/source#value> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL38C9 .
_:ub2bL120C26 <https://data.hetarchief.be/ns/source#type> "user" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL24C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#status> "active" .
_:ub2bL11C19 <https://data.hetarchief.be/ns/source#type> "primary" .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "film" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#name> "TestOrg" .
_:ub2bL109C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL109C26 .
_:ub2bL36C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL38C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL18C23 <https://data.hetarchief.be/ns/source#definition> _:ub2bL18C40 .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "golf 3" .
_:ub2bL96C26 <https://data.hetarchief.be/ns/source#id> "f0e38bfc-c9e8-08eb-bd52-fea4d6c2e012" .
_:ub2bL47C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL74C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL74C26 .
_:ub2bL72C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL72C26 .
_:ub2bL76C9 <https://data.hetarchief.be/ns/source#value> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL41C26 <https://data.hetarchief.be/ns/source#id> "91844aa8-788b-0223-a151-d825d5a6933e" .
_:ub2bL30C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL30C26 .
_:ub2bL30C26 <https://data.hetarchief.be/ns/source#id> "bb5def60-32e5-06fc-a455-e53016923d9e" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "open reel video" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#business_type> _:ub2bL16C23 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL94C9 .
_:ub2bL81C26 <https://data.hetarchief.be/ns/source#id> "903dab5d-cee3-06c5-8d56-16e578a23db6" .
_:ub2bL76C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "film" .
_:ub2bL98C26 <https://data.hetarchief.be/ns/source#id> "10d22b5f-72db-0ce7-ba58-d7013fb65b61" .
_:ub2bL112C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL109C9 <https://data.hetarchief.be/ns/source#value> "ja" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL74C9 .
_:ub2bL106C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "golf 6" .
_:ub2bL18C23 <https://data.hetarchief.be/ns/source#value> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL44C9 <https://data.hetarchief.be/ns/source#value> "ingevuld" .
_:ub2bL26C26 <https://data.hetarchief.be/ns/source#id> "afc8bfab-53cc-0421-b052-1a7b0d865628" .
_:ub2bL81C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL96C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL96C26 .
_:ub2bL38C26 <https://data.hetarchief.be/ns/source#id> "1d0cc259-4b07-01b8-aa5b-100344423db0" .
_:ub2bL21C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL21C26 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL18C23 .
_:ub2bL103C26 <https://data.hetarchief.be/ns/source#id> "9adf7d6f-b63f-0fcf-b350-b94201462f4a" .
_:ub2bL94C26 <https://data.hetarchief.be/ns/source#id> "667de27f-e39a-07d8-b659-d7c995467397" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL96C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL36C9 .
_:ub2bL94C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL94C26 .
_:ub2bL106C26 <https://data.hetarchief.be/ns/source#id> "32053d1e-e1f6-0436-9f52-8a6ce7423db4" .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "golf 1" .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#label> "5.1 - OR-ID" .
_:ub2bL103C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL103C26 .
_:ub2bL11C33 <https://data.hetarchief.be/ns/source#country> "BE" .
_:ub2bL21C26 <https://data.hetarchief.be/ns/source#id> "f8bd524b-c78f-0593-9d56-812772d23daf" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL26C9 .
_:ub2bL100C26 <https://data.hetarchief.be/ns/source#id> "9987d9fa-0230-0205-b75e-6cd219362f46" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL98C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL72C9 .
_:ub2bL47C26 <https://data.hetarchief.be/ns/source#id> "b732b771-bce9-04ae-b256-aa6fc9c23db5" .
_:ub2bL11C19 <https://data.hetarchief.be/ns/source#address> _:ub2bL11C33 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL81C9 .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "golf 2" .
_:ub2bL3C1 <https://data.hetarchief.be/ns/source#required> "false"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL30C9 <https://data.hetarchief.be/ns/source#value> "OR-testtest" .
_:ub2bL109C26 <https://data.hetarchief.be/ns/source#id> "afe9268c-c6dd-0053-bc5d-d4da5e723daa" .
_:ub2bL41C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL96C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#responsible_user> _:ub2bL120C26 .
_:ub2bL44C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL28C9 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "minidisc" .
_:ub2bL100C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL100C26 .
_:ub2bL44C26 <https://data.hetarchief.be/ns/source#id> "bcf9ceba-a988-0fc6-805f-9e087ea23dac" .
_:ub2bL28C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL28C26 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL41C9 .
_:ub2bL24C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL100C9 .
_:ub2bL76C26 <https://data.hetarchief.be/ns/source#id> "05cf38ba-2d6f-01fe-a85f-dd84aad23dae" .
_:ub2bL44C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL44C26 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL109C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#id> "4363b6fd-b7b3-088e-a274-4a9e529733fd" .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "audio CD-r" .
_:ub2bL11C33 <https://data.hetarchief.be/ns/source#postal_code> "9999" .
_:ub2bL103C9 <https://data.hetarchief.be/ns/source#value> "Description of the test organization." .
_:ub2bL18C40 <https://data.hetarchief.be/ns/source#id> "fb842ba5-5372-0767-8752-e579d2e305b4" .
_:ub2bL112C26 <https://data.hetarchief.be/ns/source#id> "efc39617-3241-0564-a350-71dfa9f66914" .
_:ub2bL24C26 <https://data.hetarchief.be/ns/source#id> "84bedd97-bde2-093f-855c-71874ec69340" .
_:ub2bL26C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL106C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL106C26 .
_:ub2bL11C33 <https://data.hetarchief.be/ns/source#city> "TestCity" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#marketing_mails_consent> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL33C9 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "betacam SP" .
_:ub2bL41C9 <https://data.hetarchief.be/ns/source#definition> _:ub2bL41C26 .
_:ub2bL36C26 <https://data.hetarchief.be/ns/source#id> "a3c5baea-e353-046e-be5f-10f956567395" .
_:ub2bL81C9 <https://data.hetarchief.be/ns/source#value> "golf 4" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#invoicing_preferences> _:ub2bL116C31 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL79C9 .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL76C9 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "DAT" .
_:ub2bL106C9 <https://data.hetarchief.be/ns/source#value> "kring 3" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL47C9 .
_:ub2bL47C9 <https://data.hetarchief.be/ns/source#value> "u-Matic" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL103C9 .
_:ub2bL30C26 <https://data.hetarchief.be/ns/source#type> "customFieldDefinition" .
_:ub2bL10C1 <https://data.hetarchief.be/ns/source#custom_fields> _:ub2bL106C9 .
```

**SPARQL CONSTRUCT query:**
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org:        <http://www.w3.org/ns/org#>
PREFIX meemoo:     <https://data.hetarchief.be/ns/organisatie#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX graphs: <https://data.hetarchief.be/graph/>
PREFIX source: <https://data.hetarchief.be/ns/source#>

CONSTRUCT {                
        ?site a org:Site;
            org:siteAddress ?siteAddress.
}
WHERE {
    # Organizations
    ?cf_orid source:id ?cf_orid_id; source:label "5.1 - OR-ID" . 
    ?o source:custom_fields [
        source:value ?orid;
        source:definition [
            #source:id "c3a10038-7a8e-0e96-bd4a-53e4668e6244"
            source:id ?cf_orid_id
        ]
    ] .
    
    # Address
    OPTIONAL {
        ?o source:addresses ?addresses.
        ?addresses  source:type ?addressType;
            source:address ?address.
    
        ?address source:line_1 ?streetAddress;
                source:postal_code ?postalCode;
                source:city ?city;
                source:country ?country. 
    }
    BIND ('https://data.hetarchief.be/id/organisatie/' AS ?ns)
    BIND (URI(CONCAT(?ns, MD5(CONCAT(?orid, "-site")))) AS ?site)
    BIND (URI(CONCAT(?ns, MD5(CONCAT(?streetAddress, ?postalCode, ?city)))) AS ?siteAddress)
    
}
```

**Comment by Tpt** [comment]
Hi! Sorry for the answer delay, I was on vacations.

The output difference is caused by a bug in the SPARQL parser that is not properly parsing nested anonymous blank nodes. I have wrote #229 that should fix this problem.

**Comment by milvala** [comment]
@Tpt No worries and thanks for fixing it!

I was wondering: what is the easiest way to update my local package and get your fixes? Usually I install from PyPi with pip, but I suppose your fixes aren't directly included on there?

**Comment by Tpt** [comment]
Thank you!

> I was wondering: what is the easiest way to update my local package and get your fixes? Usually I install from PyPi with pip, but I suppose your fixes aren't directly included on there?

The easiest way is to just wait for me to push a new release. I plan to do it later today or tomorrow. When it's done you would just need to upgrade the `pyoxigraph` package (that is a dependency of `oxrdflib`).

**Comment by Tpt** [comment]
@milvala It's now released. `pip install --upgrade pyoxigraph` should fix the bug.

**Comment by milvala** [comment]
@Tpt Cool, it seems to work (at least for Pyoxigraph)!

I'm getting a new error, however, that is related to oxrdflib (I guess).

I think it might be due to the new rdflib release? I'll start another issue.

```
caught a TypeError, retrying call to <class 'oxrdflib.OxigraphStore'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "/Users/milan/.pyenv/versions/prefect/lib/python3.9/site-packages/rdflib/namespace/__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: bind() got an unexpected keyword argument 'override'
caught a TypeError, retrying call to <class 'oxrdflib.OxigraphStore'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "/Users/milan/.pyenv/versions/prefect/lib/python3.9/site-packages/rdflib/namespace/__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: bind() got an unexpected keyword argument 'override'
caught a TypeError, retrying call to <class 'oxrdflib.OxigraphStore'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "/Users/milan/.pyenv/versions/prefect/lib/python3.9/site-packages/rdflib/namespace/__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: bind() got an unexpected keyword argument 'override'
caught a TypeError, retrying call to <class 'oxrdflib.OxigraphStore'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "/Users/milan/.pyenv/versions/prefect/lib/python3.9/site-packages/rdflib/namespace/__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: bind() got an unexpected keyword argument 'override'
caught a TypeError, retrying call to <class 'oxrdflib.OxigraphStore'>.bind without override, see https://github.com/RDFLib/rdflib/issues/1880 for more info
Traceback (most recent call last):
  File "/Users/milan/.pyenv/versions/prefect/lib/python3.9/site-packages/rdflib/namespace/__init__.py", line 627, in _store_bind
    return self.store.bind(prefix, namespace, override=override)
TypeError: bind() got an unexpected keyword argument 'override'
```
